ssh -P 2222 harry@venom.nlplab.cc:~/data_mining/final_project/outputs_models/cross_encoder_20_40_keywords_title_text_large_ensemble1/model_2.pt ./outputs_models/cross_encoder_20_40_keywords_title_text_large_ensemble1/
ssh -P 2222 harry@venom.nlplab.cc:~/data_mining/final_project/outputs_models/cross_encoder_20_40_keywords_title_text_large_ensemble2/model_2.pt ./outputs_models/cross_encoder_20_40_keywords_title_text_large_ensemble2/
ssh -P 2222 harry@venom.nlplab.cc:~/data_mining/final_project/outputs_models/cross_encoder_20_40_keywords_title_text_large_ensemble3/model_2.pt ./outputs_models/cross_encoder_20_40_keywords_title_text_large_ensemble3/
ssh -P 2222 harry@venom.nlplab.cc:~/data_mining/final_project/outputs_models/cross_encoder_20_40_keywords_title_text_large_ensemble4/model_2.pt ./outputs_models/cross_encoder_20_40_keywords_title_text_large_ensemble4/
ssh -P 2222 harry@venom.nlplab.cc:~/data_mining/final_project/outputs_models/cross_encoder_20_40_keywords_title_text_large_ensemble5/model_2.pt ./outputs_models/cross_encoder_20_40_keywords_title_text_large_ensemble5/


